# Generated by Django 4.2.5 on 2023-09-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmiosfs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-number'], 'verbose_name': 'ÖĞRENCİLER', 'verbose_name_plural': 'Student-Öğrenciler'},
        ),
    ]
