# Generated by Django 4.2.6 on 2023-10-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='defaults/aa.png', null=True, upload_to='products'),
        ),
    ]
