# Generated by Django 4.2.5 on 2023-10-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='title',
            field=models.CharField(choices=[('Team Lead', 1), ('Mid Lead ', 2), ('Junior', 3)], default=3, max_length=10),
        ),
    ]
